//! Webhook module — handles inbound events from Paystack.
//!
//! Security: every request is verified with an HMAC-SHA512 signature before
//! any payload processing.  Paystack computes the signature by running
//! HMAC-SHA512 over the raw request body using the webhook secret as the key,
//! then hex-encoding the result and sending it in `x-paystack-signature`.
//!
//! Idempotency: before crediting a wallet, the handler checks whether the
//! Paystack `reference` already exists in `transactions`.  Duplicate webhook
//! deliveries are therefore safe to receive multiple times.

use crate::error::{AppError, Result};
use crate::state::AppState;
use axum::{
    extract::State,
    http::{HeaderMap, StatusCode},
    Json,
};
use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::Sha512;
use uuid::Uuid;

/// HMAC-SHA512 type alias for readability.
type HmacSha512 = Hmac<Sha512>;

// ── Paystack payload types ────────────────────────────────────────────────────
// Both Deserialize (inbound JSON) and Serialize (stored in JSONB metadata column).

/// Top-level Paystack webhook envelope.
#[derive(Debug, Deserialize, Serialize)]
pub struct PaystackWebhookPayload {
    /// Event type, e.g. `"charge.success"`.
    pub event: String,
    pub data: PaystackData,
}

/// Core charge data from Paystack — contains the amount, status, and customer.
#[derive(Debug, Deserialize, Serialize)]
pub struct PaystackData {
    pub id: u64,
    pub domain: String,
    /// `"success"` | `"failed"` | `"abandoned"`.
    pub status: String,
    /// Unique reference string generated by Paystack — used for idempotency.
    pub reference: String,
    /// Amount in kobo (smallest NGN unit, same denomination as our DB).
    pub amount: u64,
    pub currency: String,
    pub customer: PaystackCustomer,
    #[serde(rename = "authorization")]
    pub authorization: Option<PaystackAuthorization>,
}

/// Customer record embedded in the Paystack charge data.
#[derive(Debug, Deserialize, Serialize)]
pub struct PaystackCustomer {
    pub id: u64,
    /// Used to look up the PayVault user in `users.email`.
    pub email: String,
}

/// Card / bank authorisation details — stored in JSONB metadata for records.
#[derive(Debug, Deserialize, Serialize)]
pub struct PaystackAuthorization {
    pub authorization_code: String,
    pub bank: String,
    pub account_number: String,
}

// ── Handler ───────────────────────────────────────────────────────────────────

/// POST /webhooks/paystack — receives and processes Paystack webhook events.
///
/// Verification flow:
/// 1. Extract `x-paystack-signature` header — 400 if absent.
/// 2. Compute HMAC-SHA512(body, PAYSTACK_WEBHOOK_SECRET).
/// 3. Hex-encode the digest and compare with the header value — 400 on mismatch.
/// 4. Parse the JSON body and dispatch on `event` type.
///
/// Only `charge.success` events with `status == "success"` are acted upon.
/// All other events receive a 200 acknowledgement without side effects.
#[utoipa::path(
    post,
    path = "/webhooks/paystack",
    request_body = serde_json::Value,
    responses(
        (status = 200, description = "Webhook processed successfully"),
        (status = 400, description = "Invalid signature"),
    )
)]
pub async fn paystack_webhook(
    State(state): State<AppState>,
    headers: HeaderMap, // headers extracted separately so body can be read as String
    body: String,       // raw body string — needed verbatim for HMAC verification
) -> Result<(StatusCode, Json<serde_json::Value>)> {
    // Check if Paystack is configured
    let webhook_secret = state
        .config
        .paystack_webhook_secret
        .as_ref()
        .ok_or_else(|| {
            tracing::warn!("Paystack webhook received but PAYSTACK_WEBHOOK_SECRET is not configured");
            AppError::Internal
        })?;

    // Extract Paystack-Signature header — absence means the request is not from Paystack.
    let signature = headers
        .get("x-paystack-signature")
        .and_then(|h| h.to_str().ok())
        .ok_or(AppError::InvalidWebhookSignature)?;

    // Compute HMAC-SHA512 over the raw request body using the webhook secret.
    let mut mac = HmacSha512::new_from_slice(webhook_secret.as_bytes())
        .map_err(|_| AppError::InvalidWebhookSignature)?;
    mac.update(body.as_bytes());

    // Paystack sends the signature as a lowercase hex string — compare as hex.
    // Using string equality (not mac.verify_slice) because the header is hex-encoded.
    let computed = hex::encode(mac.finalize().into_bytes());

    if computed != signature {
        tracing::warn!("Paystack webhook signature mismatch");
        return Err(AppError::InvalidWebhookSignature);
    }

    // Parse the payload now that the signature is verified.
    let payload: PaystackWebhookPayload =
        serde_json::from_str(&body).map_err(|_| AppError::Internal)?;

    // Handle charge.success — other event types are acknowledged but ignored.
    if payload.event == "charge.success" && payload.data.status == "success" {
        process_successful_charge(&state, &payload.data).await?;
    }

    Ok((
        StatusCode::OK,
        Json(serde_json::json!({ "status": "success" })),
    ))
}

// ── Internal helpers ──────────────────────────────────────────────────────────

/// Credits a user's wallet after a successful Paystack charge.
///
/// Atomicity: the wallet UPDATE and transaction INSERT run inside a single
/// Postgres transaction so the balance and audit record are always consistent.
///
/// Idempotency: checks for an existing `transactions.reference` row before
/// acting — duplicate webhook deliveries are safe to call multiple times.
async fn process_successful_charge(state: &AppState, data: &PaystackData) -> Result<()> {
    // Resolve user by email — 404 if the paying customer has no PayVault account.
    let user_id = sqlx::query_scalar::<_, Uuid>("SELECT id FROM users WHERE email = $1")
        .bind(&data.customer.email)
        .fetch_optional(&state.db)
        .await?
        .ok_or(AppError::UserNotFound)?;

    // Idempotency: skip if this reference was already processed.
    let already_processed = sqlx::query_scalar::<_, bool>(
        "SELECT EXISTS(SELECT 1 FROM transactions WHERE reference = $1)",
    )
    .bind(&data.reference)
    .fetch_one(&state.db)
    .await?;

    if already_processed {
        tracing::info!(
            "Paystack webhook: reference {} already processed, skipping",
            data.reference
        );
        return Ok(());
    }

    // ── Begin atomic Postgres transaction ─────────────────────────────────────
    let mut tx = state.db.begin().await?;

    // Atomic balance increment — safe against concurrent credits to the same wallet.
    sqlx::query(
        "UPDATE wallets \
         SET balance_kobo = balance_kobo + $1, updated_at = NOW() \
         WHERE user_id = $2",
    )
    .bind(data.amount as i64)
    .bind(user_id)
    .execute(&mut *tx)
    .await?;

    // Serialise Paystack data into JSONB for the metadata column — stored for
    // reconciliation and dispute resolution.
    let metadata = serde_json::to_value(data).unwrap_or(serde_json::Value::Null);

    // Insert immutable transaction record — sender_id is NULL for external credits.
    sqlx::query(
        r#"
        INSERT INTO transactions
            (reference, sender_id, receiver_id, amount_kobo, type, status, metadata)
        VALUES ($1, NULL, $2, $3, 'credit', 'completed', $4)
        "#,
    )
    .bind(&data.reference)
    .bind(user_id)
    .bind(data.amount as i64)
    .bind(metadata)
    .execute(&mut *tx)
    .await?;

    // ── Commit — rolls back automatically if any step above failed ────────────
    tx.commit().await?;

    tracing::info!(
        "Processed Paystack charge: {} for user {}",
        data.reference,
        user_id
    );

    Ok(())
}
